/**
 * Typed API client for PipGraph backend
 *
 * All functions return typed responses matching backend Pydantic schemas.
 * Uses environment variable NEXT_PUBLIC_API_URL for base URL.
 */

// ============================================================================
// Configuration
// ============================================================================

const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8001';
const API_PREFIX = '/api/v1/dev';

function getApiUrl(endpoint: string): string {
  return `${API_BASE}${API_PREFIX}${endpoint}`;
}

// ============================================================================
// TypeScript Types (mirroring backend Pydantic schemas)
// ============================================================================

// --- Process Note ---
export interface ProcessNoteRequest {
  name: string;
  episode_body: string;
  source_description?: string;
  reference_time?: string; // ISO datetime string
  use_para_entities?: boolean;
}

export interface ProcessNoteResponse {
  success: boolean;
  episode_uuid?: string;
  nodes_count: number;
  edges_count: number;
  error?: string;
}

// --- Get Episodic ---
export interface GetEpisodicResponse {
  success: boolean;
  episodic?: EpisodicNode;
  error?: string;
}

export interface EpisodicNode {
  uuid: string;
  name: string;
  content?: string;
  created_at: string;
  valid_at: string;
  source_description?: string;
  [key: string]: unknown; // Allow additional properties
}

// --- List Episodics ---
export interface ListEpisodicResponse {
  success: boolean;
  episodics: EpisodicNode[];
  count: number;
  error?: string;
}

// --- Create Episode ---
export interface CreateEpisodeRequest {
  content: string;
  name?: string; // Optional: auto-generated by LLM if not provided
  source_description?: string;
  reference_time?: string;
  file_path?: string;
  frontmatter?: Record<string, unknown>;
}

export interface CreateEpisodeResponse {
  success: boolean;
  uuid?: string;
  name?: string; // Returns generated or provided name
  created_at?: string;
  error?: string;
}

// --- PARA Entity ---
export interface CreateParaEntityRequest {
  para_type: 'Project' | 'Area' | 'Resource' | 'Archive';
  name: string;
  summary?: string;
  group_id?: string;
  file_path?: string;
  attributes?: Record<string, unknown>;
}

export interface CreateParaEntityResponse {
  success: boolean;
  uuid?: string;
  para_type?: string;
  name?: string;
  created_at?: string;
  error?: string;
}

export interface ParaEntity {
  uuid: string;
  name: string;
  para_type: string;
  created_at?: string;
  summary?: string;
  file_path?: string | null; // client-side filesystem binding; web does not use it, kept for contract parity
  attributes: Record<string, unknown>;
}

export interface ListParaEntitiesResponse {
  success: boolean;
  entities: ParaEntity[];
  count: number;
  error?: string;
}

// --- Link Entity-Episode ---
export interface LinkEntityEpisodeRequest {
  episodic_uuid: string;
  entity_uuid: string;
  created_at?: string;
}

export interface LinkEntityEpisodeResponse {
  success: boolean;
  edge_uuid?: string;
  episodic_uuid?: string;
  entity_uuid?: string;
  created_at?: string;
  error?: string;
}

// --- Process Existing Episode ---
export interface ProcessExistingEpisodeRequest {
  episodic_uuid: string;
  update_communities?: boolean;
}

export interface ProcessExistingEpisodeResponse {
  success: boolean;
  episode_uuid?: string;
  nodes_count: number;
  edges_count: number;
  episodic_edges_count: number;
  para_entities_updated: string[];
  error?: string;
}

// --- Make Suggestions ---
export interface MakeSuggestionsRequest {
  episodic_uuid: string;
  limit?: number; // 1-50, default 10
  min_score?: number; // 0.0-1.0, default 0.0
}

export interface ParaSuggestion {
  uuid: string;
  name: string;
  para_type: string;
  summary: string;
  score: number;
  attributes: Record<string, unknown>;
}

export interface MakeSuggestionsResponse {
  success: boolean;
  episodic_uuid?: string;
  suggestions: ParaSuggestion[];
  count: number;
  error?: string;
}

// --- PARA Tree ---
export interface TreeNode {
  id: string;
  name: string;
  type: 'Project' | 'Area' | 'Resource' | 'Archive';
  children: TreeNode[];
}

export interface GetParaTreeResponse {
  success: boolean;
  tree: TreeNode[];
  count: number;
  error?: string;
}

// --- Episodics by Entity ---
export interface GetEpisodicsByEntityResponse {
  success: boolean;
  entity_uuid?: string;
  episodics: EpisodicNode[];
  count: number;
  error?: string;
}

// --- Unlinked Episodics ---
export interface ListUnlinkedEpisodicResponse {
  success: boolean;
  episodics: EpisodicNode[];
  count: number;
  error?: string;
}

// --- LLM provider configuration (/dev/llm-config) ---
// Mirrors backend/app/api/schemas/dev.py. The api_key is never returned — only
// `api_key_set` + a 4-char `api_key_hint`. Kept in sync with the plugin client
// (pipgraph-obsidian/src/backend/types.ts) per the two-clients invariant.

export type LlmProvider = 'cloudru' | 'openrouter';

export interface LlmProviderDefaults {
  base_url: string;
  main_model: string;
  small_model: string;
  embedding_model: string;
}

export interface LlmConfigEntry {
  provider: LlmProvider;
  base_url: string;
  main_model: string;
  small_model: string;
  embedding_model: string;
  api_key_set: boolean;
  api_key_hint?: string | null;
}

export interface GetLlmConfigResponse {
  success: boolean;
  active?: LlmConfigEntry | null;
  saved?: LlmConfigEntry | null;
  restart_required: boolean;
  providers: Record<string, LlmProviderDefaults>;
  error?: string;
}

export interface UpdateLlmConfigRequest {
  provider: LlmProvider;
  api_key?: string;
  main_model?: string;
  small_model?: string;
  embedding_model?: string;
  base_url?: string;
}

export interface LlmConfigUpdateResponse {
  success: boolean;
  restart_required: boolean;
  saved?: LlmConfigEntry | null;
  warnings?: string[];
  error?: string;
}

// --- Editable prompts (/dev/prompts) ---
// Mirrors backend/app/api/schemas/dev.py. The backend owns the prompt text and
// overlays it onto graphiti; only `domain_block` is editable, `example_preview`
// is read-only. Edits apply live (no restart) and persist. Kept in sync with the
// plugin client (pipgraph-obsidian/src/backend/types.ts) per the two-clients
// invariant — the web UI does not surface these yet, but the contract is shared.

export type PromptMode = 'passthrough' | 'append' | 'replace';

export interface PromptEntry {
  key: string;
  title: string;
  description: string;
  mode: PromptMode;
  domain_block: string;
  is_customized: boolean;
  example_preview: string;
  response_model?: string | null;
  editable: boolean;
}

export interface ListPromptsResponse {
  success: boolean;
  prompts: PromptEntry[];
  error?: string;
}

export interface GetPromptResponse {
  success: boolean;
  prompt?: PromptEntry | null;
  error?: string;
}

export interface UpdatePromptRequest {
  domain_block: string;
}

export interface UpdatePromptResponse {
  success: boolean;
  prompt?: PromptEntry | null;
  error?: string;
}

// ============================================================================
// API Error Class
// ============================================================================

export class ApiError extends Error {
  constructor(
    message: string,
    public status: number,
    public response?: unknown
  ) {
    super(message);
    this.name = 'ApiError';
  }
}

// ============================================================================
// Generic Fetch Helper
// ============================================================================

async function fetchJson<T>(
  url: string,
  options: RequestInit = {}
): Promise<T> {
  const response = await fetch(url, {
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new ApiError(
      `API request failed: ${response.statusText}`,
      response.status,
      errorText
    );
  }

  return response.json();
}

// ============================================================================
// API Functions
// ============================================================================

/**
 * Process a note directly through Graphiti with full LLM pipeline
 */
export async function processNote(
  request: ProcessNoteRequest
): Promise<ProcessNoteResponse> {
  return fetchJson<ProcessNoteResponse>(getApiUrl('/process-note'), {
    method: 'POST',
    body: JSON.stringify(request),
  });
}

/**
 * Process an existing episodic node with entity extraction
 */
export async function processExistingEpisode(
  request: ProcessExistingEpisodeRequest
): Promise<ProcessExistingEpisodeResponse> {
  return fetchJson<ProcessExistingEpisodeResponse>(
    getApiUrl('/process-existing-episode'),
    {
      method: 'POST',
      body: JSON.stringify(request),
    }
  );
}

/**
 * Get a single episodic by UUID or name
 */
export async function getEpisodic(params: {
  uuid?: string;
  name?: string;
}): Promise<GetEpisodicResponse> {
  const searchParams = new URLSearchParams();
  if (params.uuid) searchParams.set('uuid', params.uuid);
  if (params.name) searchParams.set('name', params.name);

  return fetchJson<GetEpisodicResponse>(
    getApiUrl(`/episodic?${searchParams.toString()}`)
  );
}

/**
 * List all episodic nodes
 */
export async function listEpisodics(params?: {
  limit?: number;
  skip?: number;
}): Promise<ListEpisodicResponse> {
  const searchParams = new URLSearchParams();
  if (params?.limit) searchParams.set('limit', params.limit.toString());
  if (params?.skip) searchParams.set('skip', params.skip.toString());

  const query = searchParams.toString();
  return fetchJson<ListEpisodicResponse>(
    getApiUrl(`/episodic/list${query ? `?${query}` : ''}`)
  );
}

/**
 * Create a lightweight episodic node without full processing
 */
export async function createEpisode(
  request: CreateEpisodeRequest
): Promise<CreateEpisodeResponse> {
  return fetchJson<CreateEpisodeResponse>(getApiUrl('/episode'), {
    method: 'POST',
    body: JSON.stringify(request),
  });
}

/**
 * Create a PARA entity (Project/Area/Resource/Archive)
 */
export async function createParaEntity(
  request: CreateParaEntityRequest
): Promise<CreateParaEntityResponse> {
  return fetchJson<CreateParaEntityResponse>(getApiUrl('/para-entity'), {
    method: 'POST',
    body: JSON.stringify(request),
  });
}

/**
 * List PARA entities with optional filtering
 */
export async function listParaEntities(params?: {
  limit?: number;
  skip?: number;
  para_types?: string[]; // e.g., ['Project', 'Area']
}): Promise<ListParaEntitiesResponse> {
  const searchParams = new URLSearchParams();
  if (params?.limit) searchParams.set('limit', params.limit.toString());
  if (params?.skip) searchParams.set('skip', params.skip.toString());
  if (params?.para_types) {
    params.para_types.forEach((type) =>
      searchParams.append('para_types', type)
    );
  }

  const query = searchParams.toString();
  return fetchJson<ListParaEntitiesResponse>(
    getApiUrl(`/para-entities${query ? `?${query}` : ''}`)
  );
}

/**
 * Link an entity to an episode (create MENTIONS relationship)
 */
export async function linkEntityToEpisode(
  request: LinkEntityEpisodeRequest
): Promise<LinkEntityEpisodeResponse> {
  return fetchJson<LinkEntityEpisodeResponse>(
    getApiUrl('/link-entity-episode'),
    {
      method: 'POST',
      body: JSON.stringify(request),
    }
  );
}

/**
 * Get relevant PARA entity suggestions for an episodic node
 * Uses hybrid search (BM25 + vector similarity)
 */
export async function makeSuggestions(
  request: MakeSuggestionsRequest
): Promise<MakeSuggestionsResponse> {
  return fetchJson<MakeSuggestionsResponse>(getApiUrl('/make-suggestions'), {
    method: 'POST',
    body: JSON.stringify(request),
  });
}

/**
 * Get hierarchical PARA tree structure
 */
export async function getParaTree(): Promise<GetParaTreeResponse> {
  return fetchJson<GetParaTreeResponse>(getApiUrl('/para-tree'));
}

/**
 * Get episodics that mention a specific entity
 */
export async function getEpisodicsByEntity(params: {
  entity_uuid: string;
  limit?: number;
}): Promise<GetEpisodicsByEntityResponse> {
  const searchParams = new URLSearchParams();
  searchParams.set('entity_uuid', params.entity_uuid);
  if (params.limit) {
    searchParams.set('limit', params.limit.toString());
  }

  return fetchJson<GetEpisodicsByEntityResponse>(
    getApiUrl(`/episodics/by-entity?${searchParams.toString()}`)
  );
}

/**
 * Get episodics that are NOT linked to any PARA entities (unlinked notes)
 * These are "orphaned" or "unclassified" notes that need PARA categorization
 */
export async function getUnlinkedEpisodics(params?: {
  limit?: number;
}): Promise<ListUnlinkedEpisodicResponse> {
  const searchParams = new URLSearchParams();
  if (params?.limit) {
    searchParams.set('limit', params.limit.toString());
  }

  const query = searchParams.toString();
  return fetchJson<ListUnlinkedEpisodicResponse>(
    getApiUrl(`/episodic/unlinked${query ? `?${query}` : ''}`)
  );
}

/**
 * Read the current LLM provider config (active vs saved + per-provider defaults).
 */
export async function getLlmConfig(): Promise<GetLlmConfigResponse> {
  return fetchJson<GetLlmConfigResponse>(getApiUrl('/llm-config'));
}

/**
 * Persist a new LLM provider config to the backend overlay. Applies on backend
 * restart (does not rebuild the running singleton). Empty api_key keeps the
 * saved key unless the provider changed.
 */
export async function updateLlmConfig(
  request: UpdateLlmConfigRequest
): Promise<LlmConfigUpdateResponse> {
  return fetchJson<LlmConfigUpdateResponse>(getApiUrl('/llm-config'), {
    method: 'PATCH',
    body: JSON.stringify(request),
  });
}

/**
 * Delete the backend overlay, reverting to .env/settings defaults (on restart).
 */
export async function resetLlmConfig(): Promise<LlmConfigUpdateResponse> {
  return fetchJson<LlmConfigUpdateResponse>(getApiUrl('/llm-config/reset'), {
    method: 'POST',
  });
}

/**
 * List the tunable prompts (editable domain block + read-only format example).
 */
export async function listPrompts(): Promise<ListPromptsResponse> {
  return fetchJson<ListPromptsResponse>(getApiUrl('/prompts'));
}

/**
 * Fetch one tunable prompt by its registry key. Unknown key → success:false.
 */
export async function getPrompt(key: string): Promise<GetPromptResponse> {
  return fetchJson<GetPromptResponse>(
    getApiUrl(`/prompts/${encodeURIComponent(key)}`)
  );
}

/**
 * Edit a prompt's domain block. Applied live on the backend (no restart) and
 * persisted. An empty string is a deliberate empty block — use resetPrompt to
 * revert to the code default.
 */
export async function updatePrompt(
  key: string,
  request: UpdatePromptRequest
): Promise<UpdatePromptResponse> {
  return fetchJson<UpdatePromptResponse>(
    getApiUrl(`/prompts/${encodeURIComponent(key)}`),
    {
      method: 'PATCH',
      body: JSON.stringify(request),
    }
  );
}

/**
 * Reset a prompt's domain block to its code default (drops it from the overlay).
 */
export async function resetPrompt(key: string): Promise<UpdatePromptResponse> {
  return fetchJson<UpdatePromptResponse>(
    getApiUrl(`/prompts/${encodeURIComponent(key)}/reset`),
    {
      method: 'POST',
    }
  );
}

// ============================================================================
// Export all
// ============================================================================

export const api = {
  processNote,
  processExistingEpisode,
  getEpisodic,
  listEpisodics,
  createEpisode,
  createParaEntity,
  listParaEntities,
  linkEntityToEpisode,
  makeSuggestions,
  getParaTree,
  getEpisodicsByEntity,
  getUnlinkedEpisodics,
  getLlmConfig,
  updateLlmConfig,
  resetLlmConfig,
  listPrompts,
  getPrompt,
  updatePrompt,
  resetPrompt,
};

export default api;
